id = "org.knowl.system-refactor.basic"
title = "Basic Knowl System Prototype"
version = "0.1.0"
authors = ["Ryan Persson"]
license = "CC-BY-SA-4.0"
content_dir = "content"

[outputs]
static_site = true
json_indexes = true
sqlite = true

